"""Deterministic GPS/1 route generator and uploader for server/Web testing."""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import urllib.error
import urllib.request
import uuid
from datetime import datetime, time, timedelta
from pathlib import Path
from zoneinfo import ZoneInfo

from .inspection import inspect_batch
from .batch_writer import GeneratedBatch, encode_records, write_batch

SCHEMA = "gps/1"
DEFAULT_TIMEZONE = "Asia/Ho_Chi_Minh"
DEFAULT_START_TIME = time(8, 0, 0)

# A closed route in central Ho Chi Minh City. These are test coordinates only.
ROUTE = (
    (10.776889, 106.700806),
    (10.779900, 106.695900),
    (10.786650, 106.700900),
    (10.783300, 106.708250),
    (10.775550, 106.707250),
    (10.776889, 106.700806),
)


def generate_route(
    output_dir: Path,
    *,
    date: str,
    timezone: str = DEFAULT_TIMEZONE,
    seconds: int = 900,
    interval_seconds: int = 1,
    batch_records: int = 300,
    seed: str = "lifetrail-phase1-sim",
) -> list[GeneratedBatch]:
    """Generate deterministic ready/manifest pairs that follow the sync/1 contract."""
    if seconds <= 0 or interval_seconds <= 0 or batch_records <= 0:
        raise ValueError("seconds, interval_seconds and batch_records must be positive")
    total_records = seconds // interval_seconds
    if total_records < 2:
        raise ValueError("simulation must contain at least two records")

    local_day = datetime.strptime(date, "%Y-%m-%d").date()
    tz = ZoneInfo(timezone)
    start = datetime.combine(local_day, DEFAULT_START_TIME, tzinfo=tz)
    start_ts_ms = int(start.timestamp() * 1000)

    output_dir.mkdir(parents=True, exist_ok=True)
    records = _records(
        total_records=total_records,
        start_ts_ms=start_ts_ms,
        interval_ms=interval_seconds * 1000,
    )

    batches: list[GeneratedBatch] = []
    for batch_index, offset in enumerate(range(0, len(records), batch_records)):
        batch = records[offset : offset + batch_records]
        batch_id = _batch_uuid(seed, date, timezone, batch_index)
        body = encode_records(batch)
        batches.append(write_batch(output_dir, batch_id, batch, body))
    return batches


def upload_route(
    endpoint: str,
    token: str,
    batches: list[GeneratedBatch],
) -> list[dict[str, object]]:
    """Upload exact generated bytes through the real ingestion endpoint."""
    responses = []
    for batch in batches:
        manifest = inspect_batch(batch.body_path, batch.manifest_path)
        body = batch.body_path.read_bytes()
        headers = {
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/x-ndjson",
            "X-LifeTrail-Batch-Id": str(manifest["batch_id"]),
            "X-LifeTrail-Schema": SCHEMA,
            "X-LifeTrail-Content-SHA256": str(manifest["sha256"]),
            "X-LifeTrail-Byte-Length": str(manifest["byte_length"]),
            "X-LifeTrail-Record-Count": str(manifest["record_count"]),
        }
        response = _post(endpoint, headers, body)
        if (
            response.get("batch_id") != manifest["batch_id"]
            or response.get("status") != "committed"
            or response.get("record_count") != manifest["record_count"]
        ):
            raise ValueError(f"unexpected commit response: {response!r}")
        responses.append(response)
    return responses


def _records(
    *, total_records: int, start_ts_ms: int, interval_ms: int
) -> list[dict[str, object]]:
    segment_lengths = [
        _haversine_m(ROUTE[index], ROUTE[index + 1]) for index in range(len(ROUTE) - 1)
    ]
    total_distance = sum(segment_lengths)
    duration_s = ((total_records - 1) * interval_ms) / 1000.0
    speed_mps = total_distance / duration_s

    records: list[dict[str, object]] = []
    for index in range(total_records):
        fraction = index / (total_records - 1)
        lat, lon = _point_along_route(fraction, segment_lengths, total_distance)
        next_fraction = min(1.0, (index + 1) / (total_records - 1))
        next_lat, next_lon = _point_along_route(
            next_fraction, segment_lengths, total_distance
        )
        course = (
            _bearing_deg((lat, lon), (next_lat, next_lon))
            if index + 1 < total_records
            else 0.0
        )

        records.append(
            {
                "ts_ms": start_ts_ms + index * interval_ms,
                "lat": round(lat, 6),
                "lon": round(lon, 6),
                "alt_m": round(8.0 + 1.8 * math.sin(index / 55.0), 1),
                "speed_mps": round(speed_mps, 2),
                "course_deg": round(course, 1),
                "fix_quality": 1,
                "satellites": 10 + (index % 3),
                "hdop": round(0.9 + 0.1 * (index % 4), 1),
            }
        )
    return records


def _point_along_route(
    fraction: float,
    segment_lengths: list[float],
    total_distance: float,
) -> tuple[float, float]:
    target = fraction * total_distance
    walked = 0.0
    for index, segment_length in enumerate(segment_lengths):
        if target <= walked + segment_length or index == len(segment_lengths) - 1:
            ratio = 0.0 if segment_length == 0 else (target - walked) / segment_length
            ratio = max(0.0, min(1.0, ratio))
            a = ROUTE[index]
            b = ROUTE[index + 1]
            return (
                a[0] + (b[0] - a[0]) * ratio,
                a[1] + (b[1] - a[1]) * ratio,
            )
        walked += segment_length
    return ROUTE[-1]


def _batch_uuid(seed: str, date: str, timezone: str, batch_index: int) -> str:
    digest = hashlib.sha256(f"{seed}|{date}|{timezone}|{batch_index}".encode()).digest()
    return str(uuid.UUID(bytes=digest[:16], version=4))


def _haversine_m(a: tuple[float, float], b: tuple[float, float]) -> float:
    radius = 6_371_000.0
    lat1 = math.radians(a[0])
    lat2 = math.radians(b[0])
    delta_lat = math.radians(b[0] - a[0])
    delta_lon = math.radians(b[1] - a[1])
    value = (
        math.sin(delta_lat / 2) ** 2
        + math.cos(lat1) * math.cos(lat2) * math.sin(delta_lon / 2) ** 2
    )
    return radius * 2 * math.atan2(math.sqrt(value), math.sqrt(1 - value))


def _bearing_deg(a: tuple[float, float], b: tuple[float, float]) -> float:
    lat1 = math.radians(a[0])
    lat2 = math.radians(b[0])
    delta_lon = math.radians(b[1] - a[1])
    y = math.sin(delta_lon) * math.cos(lat2)
    x = math.cos(lat1) * math.sin(lat2) - math.sin(lat1) * math.cos(lat2) * math.cos(
        delta_lon
    )
    return (math.degrees(math.atan2(y, x)) + 360.0) % 360.0


def _post(endpoint: str, headers: dict[str, str], body: bytes) -> dict[str, object]:
    request = urllib.request.Request(
        endpoint, data=body, headers=headers, method="POST"
    )
    try:
        with urllib.request.urlopen(request, timeout=15) as response:
            if response.status != 200:
                raise ValueError(f"server returned HTTP {response.status}")
            payload = json.loads(response.read())
    except urllib.error.HTTPError as error:
        details = error.read().decode("utf-8", errors="replace")
        raise ValueError(f"server returned HTTP {error.code}: {details}") from error
    if not isinstance(payload, dict):
        raise ValueError("server returned a non-object response")
    return payload


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Generate deterministic gps/1 Batches and optionally upload them to LifeTrail."
    )
    parser.add_argument("--date", required=True, help="Owner-local date, YYYY-MM-DD")
    parser.add_argument("--timezone", default=DEFAULT_TIMEZONE)
    parser.add_argument(
        "--output", type=Path, default=Path("tools/fixtures/simulated-route")
    )
    parser.add_argument("--seconds", type=int, default=900)
    parser.add_argument("--interval-seconds", type=int, default=1)
    parser.add_argument("--batch-records", type=int, default=300)
    parser.add_argument("--seed", default="lifetrail-phase1-sim")
    parser.add_argument("--endpoint")
    parser.add_argument("--token")
    return parser


def main() -> int:
    args = build_parser().parse_args()
    if bool(args.endpoint) != bool(args.token):
        raise SystemExit("--endpoint and --token must be supplied together")

    batches = generate_route(
        args.output,
        date=args.date,
        timezone=args.timezone,
        seconds=args.seconds,
        interval_seconds=args.interval_seconds,
        batch_records=args.batch_records,
        seed=args.seed,
    )
    result: dict[str, object] = {
        "date": args.date,
        "timezone": args.timezone,
        "output": str(args.output),
        "batch_count": len(batches),
        "record_count": sum(batch.record_count for batch in batches),
        "batches": [batch.batch_id for batch in batches],
    }

    if args.endpoint:
        result["responses"] = upload_route(args.endpoint, args.token, batches)

    print(json.dumps(result, indent=2, sort_keys=True))
    return 0
